apiVersion: v1
description: A Gravitee.io API Management Helm chart for Kubernetes
name: graviteeio-apim
version: 1.25.2
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4